name: visiumhd
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - ipykernel

  # single-cell / spatial
  - scanpy>=1.9
  - anndata
  - squidpy>=1.4
  - spatialdata
  - spatialdata-io

  # plotting
  - napari
  - plotly

  # misc
  - tqdm
  - statsmodels

